Repository The-Aether-Team/The-Aether-II, pull requests merged in 2024-07, with the labels that each got.

#337 improv: highfields burrukai visuals
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/animation/BurrukaiAnimation.java
  src/main/resources/assets/aether_ii/textures/entity/mobs/burrukai/highfields/burrukai_highfields.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/burrukai/highfields/burrukai_highfields_baby.png
Labels: status/pending-review

#340 feat: burrukai variants
  src/generated/resources/assets/aether_ii/lang/en_us.json
  src/generated/resources/assets/aether_ii/models/item/arctic_burrukai_spawn_egg.json
  src/generated/resources/assets/aether_ii/models/item/magnetic_burrukai_spawn_egg.json
  src/generated/resources/data/aether_ii/loot_table/entities/arctic_burrukai.json
  src/generated/resources/data/aether_ii/loot_table/entities/magnetic_burrukai.json
  src/generated/resources/data/aether_ii/tags/entity_type/burrukai.json
  src/generated/resources/data/aether_ii/worldgen/biome/enduring_woodland.json
  src/generated/resources/data/aether_ii/worldgen/biome/frigid_sierra.json
  src/generated/resources/data/aether_ii/worldgen/biome/frozen_lakes.json
  src/generated/resources/data/aether_ii/worldgen/biome/glistening_swamp.json
  src/generated/resources/data/aether_ii/worldgen/biome/magnetic_scar.json
  src/generated/resources/data/aether_ii/worldgen/biome/sheer_tundra.json
  src/generated/resources/data/aether_ii/worldgen/biome/turquoise_forest.json
  src/generated/resources/data/aether_ii/worldgen/biome/violet_highwoods.json
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIModelLayers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIRenderers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/BiomeVariantPresets.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/BurrukaiRenderer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/KirridRenderer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/burrukai/AbstractBurrukaiBabyModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/burrukai/AbstractBurrukaiModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/burrukai/ArcticBurrukaiModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/burrukai/BurrukaiBabyModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/burrukai/BurrukaiModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/burrukai/HighfieldsBurrukaiBabyModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/kirrid/AbstractKirridBabyModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/kirrid/AbstractKirridModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/kirrid/ArcticKirridBabyModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/kirrid/ArcticKirridModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/kirrid/HighfieldsKirridBabyModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/kirrid/HighfieldsKirridModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/kirrid/MagneticKirridBabyModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/kirrid/MagneticKirridModel.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIItemModelData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIILanguageData.java
  src/main/java/com/aetherteam/aetherii/data/generators/loot/AetherIIEntityLoot.java
  src/main/java/com/aetherteam/aetherii/data/generators/tags/AetherIIEntityTagData.java
  src/main/java/com/aetherteam/aetherii/data/resources/builders/highlands/HighlandsBiomeBuilders.java
  src/main/java/com/aetherteam/aetherii/entity/AetherIIEntityTypes.java
  src/main/java/com/aetherteam/aetherii/item/AetherIICreativeTabs.java
  src/main/java/com/aetherteam/aetherii/item/AetherIIItems.java
  src/main/resources/assets/aether_ii/textures/entity/mobs/burrukai/arctic/burrukai_arctic.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/burrukai/arctic/burrukai_arctic_baby.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/burrukai/magnetic/burrukai_magnetic.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/burrukai/magnetic/burrukai_magnetic_baby.png
Labels: status/pending-review

#335 feat: outpost campfire and multiblock system
  gradle.properties
  src/generated/resources/assets/aether_ii/blockstates/outpost_campfire.json
  src/generated/resources/assets/aether_ii/lang/en_us.json
  src/generated/resources/assets/aether_ii/models/block/outpost_campfire.json
  src/generated/resources/assets/aether_ii/models/item/outpost_campfire.json
  src/generated/resources/data/aether_ii/loot_table/blocks/outpost_campfire.json
  src/main/java/com/aetherteam/aetherii/block/AetherIIBlocks.java
  src/main/java/com/aetherteam/aetherii/block/furniture/MultiBlock.java
  src/main/java/com/aetherteam/aetherii/block/furniture/OutpostCampfireBlock.java
  src/main/java/com/aetherteam/aetherii/blockentity/AetherIIBlockEntityTypes.java
  src/main/java/com/aetherteam/aetherii/blockentity/OutpostCampfireBlockEntity.java
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIModelLayers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIRenderers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/blockentity/OutpostCampfireRenderer.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIBlockStateData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIItemModelData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIILanguageData.java
  src/main/java/com/aetherteam/aetherii/data/generators/loot/AetherIIBlockLoot.java
  src/main/java/com/aetherteam/aetherii/data/providers/AetherIIBlockStateProvider.java
  src/main/java/com/aetherteam/aetherii/data/providers/AetherIIItemModelProvider.java
  src/main/java/com/aetherteam/aetherii/item/AetherIICreativeTabs.java
  src/main/java/com/aetherteam/aetherii/mixin/mixins/common/accessor/BlockAccessor.java
  src/main/resources/aether_ii.mixins.json
  src/main/resources/assets/aether_ii/textures/entity/tiles/furniture/outpost_campfire.png
  src/main/resources/assets/minecraft/atlases/blocks.json
  src/main/resources/data/aether_ii/structure/outpost/outpost.nbt
  src/main/resources/data/aether_ii/structure/outpost/tall_outpost.nbt
Labels: status/pending-review

#347 feat: armor textures
  src/main/java/com/aetherteam/aetherii/item/AetherIICreativeTabs.java
  src/main/resources/assets/aether_ii/textures/item/armor/arkenium_boots.png
  src/main/resources/assets/aether_ii/textures/item/armor/arkenium_chestplate.png
  src/main/resources/assets/aether_ii/textures/item/armor/arkenium_gloves.png
  src/main/resources/assets/aether_ii/textures/item/armor/arkenium_helmet.png
  src/main/resources/assets/aether_ii/textures/item/armor/arkenium_leggings.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_boots.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_boots_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_chestplate.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_chestplate_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_gloves.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_gloves_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_helmet.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_helmet_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_leggings.png
  src/main/resources/assets/aether_ii/textures/item/armor/burrukai_pelt_leggings_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/gravitite_boots.png
  src/main/resources/assets/aether_ii/textures/item/armor/gravitite_chestplate.png
  src/main/resources/assets/aether_ii/textures/item/armor/gravitite_gloves.png
  src/main/resources/assets/aether_ii/textures/item/armor/gravitite_helmet.png
  src/main/resources/assets/aether_ii/textures/item/armor/gravitite_leggings.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_boots.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_boots_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_chestplate.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_chestplate_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_gloves.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_gloves_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_helmet.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_helmet_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_leggings.png
  src/main/resources/assets/aether_ii/textures/item/armor/taegore_hide_leggings_dyed.png
  src/main/resources/assets/aether_ii/textures/item/armor/zanite_boots.png
  src/main/resources/assets/aether_ii/textures/item/armor/zanite_chestplate.png
  src/main/resources/assets/aether_ii/textures/item/armor/zanite_gloves.png
  src/main/resources/assets/aether_ii/textures/item/armor/zanite_helmet.png
  src/main/resources/assets/aether_ii/textures/item/armor/zanite_leggings.png
  src/main/resources/assets/aether_ii/textures/models/accessory/handwear/arkenium_gloves_accessory.png
  src/main/resources/assets/aether_ii/textures/models/accessory/handwear/burrukai_pelt_gloves_accessory.png
  src/main/resources/assets/aether_ii/textures/models/accessory/handwear/burrukai_pelt_gloves_accessory_dyed.png
  src/main/resources/assets/aether_ii/textures/models/accessory/handwear/gravitite_gloves_accessory.png
  src/main/resources/assets/aether_ii/textures/models/accessory/handwear/taegore_hide_gloves_accessory.png
  src/main/resources/assets/aether_ii/textures/models/accessory/handwear/taegore_hide_gloves_accessory_dyed.png
  src/main/resources/assets/aether_ii/textures/models/accessory/handwear/zanite_gloves_accessory.png
  src/main/resources/assets/aether_ii/textures/models/armor/arkenium_layer_1.png
  src/main/resources/assets/aether_ii/textures/models/armor/arkenium_layer_2.png
  src/main/resources/assets/aether_ii/textures/models/armor/burrukai_pelt_layer_1.png
  src/main/resources/assets/aether_ii/textures/models/armor/burrukai_pelt_layer_1_dyed.png
  src/main/resources/assets/aether_ii/textures/models/armor/burrukai_pelt_layer_2.png
  src/main/resources/assets/aether_ii/textures/models/armor/burrukai_pelt_layer_2_dyed.png
  src/main/resources/assets/aether_ii/textures/models/armor/gravitite_layer_1.png
  src/main/resources/assets/aether_ii/textures/models/armor/gravitite_layer_2.png
  src/main/resources/assets/aether_ii/textures/models/armor/taegore_hide_layer_1.png
  src/main/resources/assets/aether_ii/textures/models/armor/taegore_hide_layer_1_dyed.png
  src/main/resources/assets/aether_ii/textures/models/armor/taegore_hide_layer_2.png
  src/main/resources/assets/aether_ii/textures/models/armor/taegore_hide_layer_2_dyed.png
  src/main/resources/assets/aether_ii/textures/models/armor/zanite_layer_1.png
  src/main/resources/assets/aether_ii/textures/models/armor/zanite_layer_2.png
Labels: status/pending-review

#348 feat: enchanted short grass, generation, and setup for irradiated leaf shading
  src/generated/resources/assets/aether_ii/blockstates/aether_long_grass.json
  src/generated/resources/assets/aether_ii/blockstates/aether_medium_grass.json
  src/generated/resources/assets/aether_ii/blockstates/aether_short_grass.json
  src/generated/resources/assets/aether_ii/models/block/enchanted_aether_long_grass.json
  src/generated/resources/assets/aether_ii/models/block/enchanted_aether_medium_grass.json
  src/generated/resources/assets/aether_ii/models/block/enchanted_aether_short_grass.json
  src/generated/resources/data/aether_ii/worldgen/configured_feature/aether_grass_bonemeal.json
  src/generated/resources/data/aether_ii/worldgen/configured_feature/long_grass_patch.json
  src/generated/resources/data/aether_ii/worldgen/configured_feature/medium_grass_patch.json
  src/generated/resources/data/aether_ii/worldgen/configured_feature/short_grass_patch.json
  src/generated/resources/data/aether_ii/worldgen/noise_settings/highlands.json
  src/main/java/com/aetherteam/aetherii/block/AetherIIBlockBuilders.java
  src/main/java/com/aetherteam/aetherii/block/AetherIIBlocks.java
  src/main/java/com/aetherteam/aetherii/block/natural/AetherTallGrassBlock.java
  src/main/java/com/aetherteam/aetherii/block/natural/IrradiatedLeavesBlock.java
  src/main/java/com/aetherteam/aetherii/block/natural/Snowable.java
  src/main/java/com/aetherteam/aetherii/client/AetherIIColorResolvers.java
  src/main/java/com/aetherteam/aetherii/data/providers/AetherIIBlockStateProvider.java
  src/main/java/com/aetherteam/aetherii/data/resources/builders/AetherIIFeatureBuilders.java
  src/main/java/com/aetherteam/aetherii/data/resources/builders/highlands/HighlandsSurfaceBuilders.java
  src/main/java/com/aetherteam/aetherii/data/resources/registries/features/AetherIIVegetationFeatures.java
  src/main/java/com/aetherteam/aetherii/event/hooks/BlockInteractionHooks.java
  src/main/java/com/aetherteam/aetherii/mixin/mixins/common/ServerLevelMixin.java
  src/main/java/com/aetherteam/aetherii/world/feature/AetherGrassFeature.java
  src/main/java/com/aetherteam/aetherii/world/feature/AetherIIFeatures.java
  src/main/java/com/aetherteam/aetherii/world/feature/ArcticSnowAndFreezeFeature.java
  src/main/resources/assets/aether_ii/textures/block/natural/enchanted_aether_long_grass.png
  src/main/resources/assets/aether_ii/textures/block/natural/enchanted_aether_medium_grass.png
  src/main/resources/assets/aether_ii/textures/block/natural/enchanted_aether_short_grass.png
  src/main/resources/assets/aether_ii/textures/block/natural/irradiated_greatboa_leaves.png
  src/main/resources/assets/aether_ii/textures/block/natural/irradiated_greatoak_leaves.png
  src/main/resources/assets/aether_ii/textures/block/natural/irradiated_greatroot_leaves.png
  src/main/resources/assets/aether_ii/textures/block/natural/irradiated_skybirch_leaves.png
  src/main/resources/assets/aether_ii/textures/block/natural/irradiated_skypine_leaves.png
  src/main/resources/assets/aether_ii/textures/block/natural/irradiated_skyplane_leaves.png
  src/main/resources/assets/aether_ii/textures/block/natural/irradiated_skyroot_leaves.png
  src/main/resources/assets/aether_ii/textures/block/natural/irradiated_wisproot_leaves.png
  src/main/resources/assets/aether_ii/textures/block/natural/irradiated_wisptop_leaves.png
Labels: status/pending-review

#342 feat: aechor plant
  src/generated/resources/assets/aether_ii/blockstates/aechor_cutting.json
  src/generated/resources/assets/aether_ii/blockstates/potted_aechor_cutting.json
  src/generated/resources/assets/aether_ii/lang/en_us.json
  src/generated/resources/assets/aether_ii/models/block/aechor_cutting.json
  src/generated/resources/assets/aether_ii/models/block/potted_aechor_cutting.json
  src/generated/resources/assets/aether_ii/models/item/aechor_cutting.json
  src/generated/resources/assets/aether_ii/models/item/aechor_plant_spawn_egg.json
  src/generated/resources/data/aether_ii/aether_ii/damage_resistance/aechor_plant.json
  src/generated/resources/data/aether_ii/loot_table/blocks/aechor_cutting.json
  src/generated/resources/data/aether_ii/loot_table/blocks/potted_aechor_cutting.json
  src/generated/resources/data/aether_ii/loot_table/entities/aechor_plant.json
  src/generated/resources/data/aether_ii/tags/block/aechor_plant_spawnable_on.json
  src/generated/resources/data/aether_ii/tags/entity_type/spawning/aerclouds.json
  src/generated/resources/data/aether_ii/worldgen/biome/enduring_woodland.json
  src/generated/resources/data/aether_ii/worldgen/biome/flourishing_field.json
  src/generated/resources/data/aether_ii/worldgen/biome/frigid_sierra.json
  src/generated/resources/data/aether_ii/worldgen/biome/frozen_lakes.json
  src/generated/resources/data/aether_ii/worldgen/biome/glistening_swamp.json
  src/generated/resources/data/aether_ii/worldgen/biome/magnetic_scar.json
  src/generated/resources/data/aether_ii/worldgen/biome/sheer_tundra.json
  src/generated/resources/data/aether_ii/worldgen/biome/shimmering_basin.json
  src/generated/resources/data/aether_ii/worldgen/biome/shrouded_forest.json
  src/generated/resources/data/aether_ii/worldgen/biome/turquoise_forest.json
  src/generated/resources/data/aether_ii/worldgen/biome/verdant_woods.json
  src/generated/resources/data/aether_ii/worldgen/biome/violet_highwoods.json
  src/generated/resources/data/minecraft/tags/block/flower_pots.json
  src/generated/resources/data/minecraft/tags/block/small_flowers.json
  src/main/java/com/aetherteam/aetherii/AetherIITags.java
  src/main/java/com/aetherteam/aetherii/block/AetherIIBlocks.java
  src/main/java/com/aetherteam/aetherii/block/natural/AechorCuttingBlock.java
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIModelLayers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIRenderers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/AechorPlantRenderer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/ToxicDartRenderer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/animation/AechorPlantAnimation.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/AechorPlantModel.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIBlockStateData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIItemModelData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIILanguageData.java
  src/main/java/com/aetherteam/aetherii/data/generators/loot/AetherIIBlockLoot.java
  src/main/java/com/aetherteam/aetherii/data/generators/loot/AetherIIEntityLoot.java
  src/main/java/com/aetherteam/aetherii/data/generators/tags/AetherIIBlockTagData.java
  src/main/java/com/aetherteam/aetherii/data/generators/tags/AetherIIEntityTagData.java
  src/main/java/com/aetherteam/aetherii/data/resources/builders/highlands/HighlandsBiomeBuilders.java
  src/main/java/com/aetherteam/aetherii/data/resources/registries/AetherIIDamageResistances.java
  src/main/java/com/aetherteam/aetherii/entity/AetherIIEntityTypes.java
  src/main/java/com/aetherteam/aetherii/entity/monster/AechorPlant.java
  src/main/java/com/aetherteam/aetherii/entity/projectile/ToxicDart.java
  src/main/java/com/aetherteam/aetherii/item/AetherIICreativeTabs.java
  src/main/java/com/aetherteam/aetherii/item/AetherIIItems.java
  src/main/resources/assets/aether_ii/textures/block/natural/aechor_cutting.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/aechor_plant/aechor_plant.png
  src/main/resources/assets/aether_ii/textures/entity/projectile/toxic_dart.png
Labels: status/pending-review

#354 refactor: better portal placement and cloud darkening
  src/main/java/com/aetherteam/aetherii/block/portal/AetherPortalBlock.java
  src/main/java/com/aetherteam/aetherii/block/portal/AetherPortalForcer.java
  src/main/java/com/aetherteam/aetherii/client/event/hooks/attachment/DimensionRenderEffectHooks.java
  src/main/java/com/aetherteam/aetherii/client/renderer/level/HighlandsSpecialEffects.java
Labels: status/pending-review

#362 feat: skyroot buckets
  src/generated/resources/assets/aether_ii/lang/en_us.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_axolotl_bucket.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_bucket.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_cod_bucket.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_milk_bucket.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_powder_snow_bucket.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_pufferfish_bucket.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_salmon_bucket.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_tadpole_bucket.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_tropical_fish_bucket.json
  src/generated/resources/assets/aether_ii/models/item/skyroot_water_bucket.json
  src/generated/resources/data/aether_ii/advancement/recipes/misc/skyroot_bucket.json
  src/generated/resources/data/aether_ii/data_maps/item/bucket_replacement.json
  src/generated/resources/data/aether_ii/recipe/skyroot_bucket.json
  src/generated/resources/data/aether_ii/tags/block/allowed_bucket_pickup.json
  src/generated/resources/data/aether_ii/tags/fluid/allowed_bucket_pickup.json
  src/main/java/com/aetherteam/aetherii/AetherII.java
  src/main/java/com/aetherteam/aetherii/AetherIITags.java
  src/main/java/com/aetherteam/aetherii/block/AetherIICauldronInteractions.java
  src/main/java/com/aetherteam/aetherii/block/AetherIIDispenseBehaviors.java
  src/main/java/com/aetherteam/aetherii/data/AetherIIData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIDataMapData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIItemModelData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIILanguageData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIRecipeData.java
  src/main/java/com/aetherteam/aetherii/data/generators/tags/AetherIIBlockTagData.java
  src/main/java/com/aetherteam/aetherii/data/generators/tags/AetherIIFluidTagData.java
  src/main/java/com/aetherteam/aetherii/data/resources/BucketReplacement.java
  src/main/java/com/aetherteam/aetherii/data/resources/registries/AetherIIDataMaps.java
  src/main/java/com/aetherteam/aetherii/event/hooks/EntityInteractionHooks.java
  src/main/java/com/aetherteam/aetherii/event/listeners/EntityInteractionListener.java
  src/main/java/com/aetherteam/aetherii/item/AetherIICreativeTabs.java
  src/main/java/com/aetherteam/aetherii/item/AetherIIItems.java
  src/main/java/com/aetherteam/aetherii/item/miscellaneous/bucket/SkyrootBucketItem.java
  src/main/java/com/aetherteam/aetherii/item/miscellaneous/bucket/SkyrootMilkBucketItem.java
  src/main/java/com/aetherteam/aetherii/item/miscellaneous/bucket/SkyrootMobBucketItem.java
  src/main/java/com/aetherteam/aetherii/item/miscellaneous/bucket/SkyrootSolidBucketItem.java
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_axolotl_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_cod_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_milk_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_powder_snow_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_pufferfish_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_salmon_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_tadpole_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_tropical_fish_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_water_bucket.png
Labels: status/pending-review

#346 feat: campfire respawning
  src/generated/resources/assets/aether_ii/blockstates/outpost_campfire.json
  src/generated/resources/assets/aether_ii/lang/en_us.json
  src/generated/resources/assets/aether_ii/models/block/outpost_campfire.json
  src/generated/resources/assets/aether_ii/models/block/outpost_campfire_east.json
  src/generated/resources/assets/aether_ii/models/block/outpost_campfire_north.json
  src/generated/resources/assets/aether_ii/models/block/outpost_campfire_south.json
  src/generated/resources/assets/aether_ii/models/block/outpost_campfire_west.json
  src/generated/resources/assets/aether_ii/models/item/outpost_campfire.json
  src/main/java/com/aetherteam/aetherii/AetherII.java
  src/main/java/com/aetherteam/aetherii/attachment/AetherIIDataAttachments.java
  src/main/java/com/aetherteam/aetherii/attachment/entity/DroppedItemAttachment.java
  src/main/java/com/aetherteam/aetherii/attachment/player/DimensionTeleportationAttachment.java
  src/main/java/com/aetherteam/aetherii/attachment/player/OutpostTrackerAttachment.java
  src/main/java/com/aetherteam/aetherii/attachment/player/PortalTeleportationAttachment.java
  src/main/java/com/aetherteam/aetherii/block/AetherIIBlocks.java
  src/main/java/com/aetherteam/aetherii/block/furniture/MultiBlock.java
  src/main/java/com/aetherteam/aetherii/block/furniture/OutpostCampfireBlock.java
  src/main/java/com/aetherteam/aetherii/block/portal/AetherPortalBlock.java
  src/main/java/com/aetherteam/aetherii/blockentity/MultiBlockEntity.java
  src/main/java/com/aetherteam/aetherii/blockentity/OutpostCampfireBlockEntity.java
  src/main/java/com/aetherteam/aetherii/client/AetherIIClient.java
  src/main/java/com/aetherteam/aetherii/client/event/hooks/PlayerRespawnClientHooks.java
  src/main/java/com/aetherteam/aetherii/client/event/listeners/PlayerRespawnClientListeners.java
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIModelLayers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIOverlays.java
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIRenderers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/block/model/baked/AmbientOcclusionLightModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/block/model/baked/FastModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/blockentity/OutpostCampfireRenderer.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIBlockStateData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIIItemModelData.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIILanguageData.java
  src/main/java/com/aetherteam/aetherii/data/providers/AetherIIBlockStateProvider.java
  src/main/java/com/aetherteam/aetherii/data/providers/AetherIIItemModelProvider.java
  src/main/java/com/aetherteam/aetherii/event/hooks/BlockInteractionHooks.java
  src/main/java/com/aetherteam/aetherii/event/hooks/OutpostTrackerHooks.java
  src/main/java/com/aetherteam/aetherii/event/hooks/attachment/DimensionTeleportationHooks.java
  src/main/java/com/aetherteam/aetherii/event/listeners/BlockInteractionListener.java
  src/main/java/com/aetherteam/aetherii/event/listeners/OutpostTrackerListener.java
  src/main/java/com/aetherteam/aetherii/event/listeners/attachment/AerbunnyMountListener.java
  src/main/java/com/aetherteam/aetherii/event/listeners/attachment/DimensionTeleportationListener.java
  src/main/java/com/aetherteam/aetherii/mixin/mixins/client/ReceivingLevelScreenMixin.java
  src/main/java/com/aetherteam/aetherii/mixin/mixins/client/accessor/DeathScreenAccessor.java
  src/main/java/com/aetherteam/aetherii/mixin/mixins/common/EntityMixin.java
  src/main/java/com/aetherteam/aetherii/mixin/mixins/common/accessor/BlockAccessor.java
  src/main/java/com/aetherteam/aetherii/network/packet/OutpostTrackerSyncPacket.java
  src/main/java/com/aetherteam/aetherii/network/packet/clientbound/SetVehiclePacket.java
  src/main/java/com/aetherteam/aetherii/network/packet/serverbound/OutpostRespawnPacket.java
  src/main/resources/aether_ii.mixins.json
  src/main/resources/assets/aether_ii/models/block/template_outpost_campfire_east.json
  src/main/resources/assets/aether_ii/models/block/template_outpost_campfire_north.json
  src/main/resources/assets/aether_ii/models/block/template_outpost_campfire_south.json
  src/main/resources/assets/aether_ii/models/block/template_outpost_campfire_west.json
  src/main/resources/assets/aether_ii/textures/block/furniture/outpost_campfire.png
  src/main/resources/assets/aether_ii/textures/entity/tiles/furniture/outpost_campfire.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/outpost_campfire.png
  src/main/resources/data/aether_ii/structure/outpost/outpost.nbt
  src/main/resources/data/aether_ii/structure/outpost/tall_outpost.nbt
Labels: status/pending-review

#371 fix: bush fence connectivity and artisan bench saw render
  src/main/java/com/aetherteam/aetherii/block/natural/FullAetherBushBlock.java
  src/main/resources/assets/aether_ii/models/block/template_artisans_bench.json
  src/main/resources/assets/aether_ii/textures/block/utility/masonry_bench.png
Labels: status/pending-review

#380 feat: updated blight mob models and textures
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/CockatriceRenderer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/TempestRenderer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/layers/CockatriceEmissiveLayer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/layers/TempestEmissiveLayer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/CockatriceModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/TempestModel.java
  src/main/resources/assets/aether_ii/textures/entity/mobs/cockatrice/cockatrice.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/cockatrice/cockatrice_emissive.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/tempest/tempest.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/tempest/tempest_emissive.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/tempest/tempest_layer.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/tempest/tempest_layer_glow.png
Labels: status/in-progress

#383 feat: updated and improved visuals for many features
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/CockatriceModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/TempestModel.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/burrukai/ArcticBurrukaiModel.java
  src/main/java/com/aetherteam/aetherii/item/AetherIIItems.java
  src/main/resources/assets/aether_ii/textures/block/natural/valkyrie_sprout_0.png
  src/main/resources/assets/aether_ii/textures/block/natural/valkyrie_sprout_1.png
  src/main/resources/assets/aether_ii/textures/block/natural/valkyrie_sprout_2.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/burrukai/arctic/burrukai_arctic.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/burrukai/arctic/burrukai_arctic_baby.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/cockatrice/cockatrice.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/cockatrice/cockatrice_emissive.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/taegore/arctic/taegore_arctic.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/taegore/arctic/taegore_arctic_baby.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/taegore/highfields/taegore_highfields.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/taegore/highfields/taegore_highfields_baby.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/taegore/magnetic/taegore_magnetic.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/taegore/magnetic/taegore_magnetic_baby.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/tempest/tempest.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/tempest/tempest_emissive.png
  src/main/resources/assets/aether_ii/textures/item/materials/brettl_cane.png
  src/main/resources/assets/aether_ii/textures/item/materials/brettl_grass.png
  src/main/resources/assets/aether_ii/textures/item/materials/brettl_rope.png
  src/main/resources/assets/aether_ii/textures/item/materials/burrukai_pelt.png
  src/main/resources/assets/aether_ii/textures/item/materials/cloudtwine.png
  src/main/resources/assets/aether_ii/textures/item/materials/scatterglass_shard.png
  src/main/resources/assets/aether_ii/textures/item/materials/skyroot_pinecone.png
  src/main/resources/assets/aether_ii/textures/item/materials/taegore_hide.png
  src/main/resources/assets/aether_ii/textures/item/materials/valkyrie_wings.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_axolotl_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_cod_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_milk_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_powder_snow_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_pufferfish_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_salmon_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_tadpole_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_tropical_fish_bucket.png
  src/main/resources/assets/aether_ii/textures/item/miscellaneous/skyroot_water_bucket.png
  src/main/resources/assets/aether_ii/textures/item/tools/arkenium_shears.png
Labels: status/pending-review, feat/art

#384 improv: lang and texture changes
  src/generated/resources/assets/aether_ii/lang/en_us.json
  src/generated/resources/assets/aether_ii/models/block/aether_grass_block.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/aechor_plant.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/aerbunny.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/arctic_burrukai.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/arctic_kirrid.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/arctic_taegore.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/cockatrice.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/flying_cow.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/highfields_burrukai.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/highfields_kirrid.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/highfields_taegore.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/magnetic_burrukai.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/magnetic_kirrid.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/magnetic_taegore.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/moa.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/phyg.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/sheepuff.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/skyroot_lizard.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/tempest.json
  src/generated/resources/data/aether_ii/aether_ii/bestiary_entry/zephyr.json
  src/main/java/com/aetherteam/aetherii/api/guidebook/BestiaryEntry.java
  src/main/java/com/aetherteam/aetherii/attachment/player/GuidebookDiscoveryAttachment.java
  src/main/java/com/aetherteam/aetherii/block/furniture/OutpostCampfireBlock.java
  src/main/java/com/aetherteam/aetherii/client/event/listeners/GuiExtensionListener.java
  src/main/java/com/aetherteam/aetherii/client/gui/component/toast/GuidebookToast.java
  src/main/java/com/aetherteam/aetherii/client/gui/screen/guidebook/GuidebookEquipmentScreen.java
  src/main/java/com/aetherteam/aetherii/client/gui/screen/guidebook/discovery/BestiarySection.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/TempestThunderballRenderer.java
  src/main/java/com/aetherteam/aetherii/data/generators/AetherIILanguageData.java
  src/main/java/com/aetherteam/aetherii/data/providers/AetherIIBlockStateProvider.java
  src/main/java/com/aetherteam/aetherii/data/providers/AetherIILanguageProvider.java
  src/main/java/com/aetherteam/aetherii/data/resources/registries/AetherIIBestiaryEntries.java
  src/main/java/com/aetherteam/aetherii/event/listeners/attachment/DimensionTeleportationListener.java
  src/main/java/com/aetherteam/aetherii/item/AetherIICreativeTabs.java
  src/main/java/com/aetherteam/aetherii/item/AetherIIItems.java
  src/main/java/com/aetherteam/aetherii/item/miscellaneous/BiomeMobSpawnEggItem.java
  src/main/java/com/aetherteam/aetherii/network/packet/clientbound/GuidebookToastPacket.java
  src/main/resources/assets/aether_ii/textures/gui/sprites/toast/guidebook_discovery.png
  src/main/resources/assets/aether_ii/textures/gui/sprites/toast/guidebook_journal.png
  src/main/resources/assets/aether_ii/textures/item/materials/arctic_snowball.png
Labels: status/pending-review

#387 improv: new zephyr assets
  src/generated/resources/data/aether_ii/tags/entity_type/aether_mobs.json
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIModelLayers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/AetherIIRenderers.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/TempestRenderer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/ZephyrRenderer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/ZephyrWebbingBallRenderer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/animation/ZephyrAnimation.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/layers/ZephyrTransparencyLayer.java
  src/main/java/com/aetherteam/aetherii/client/renderer/entity/model/ZephyrModel.java
  src/main/java/com/aetherteam/aetherii/data/generators/tags/AetherIIEntityTagData.java
  src/main/java/com/aetherteam/aetherii/entity/AetherIIEntityTypes.java
  src/main/java/com/aetherteam/aetherii/entity/monster/Zephyr.java
  src/main/java/com/aetherteam/aetherii/entity/projectile/ZephyrWebbingBall.java
  src/main/resources/assets/aether_ii/textures/entity/mobs/zephyr/zephyr.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/zephyr/zephyr_classic.png
  src/main/resources/assets/aether_ii/textures/entity/mobs/zephyr/zephyr_layer.png
  src/main/resources/assets/aether_ii/textures/entity/projectile/zephyr_webbing_ball.png
Labels: status/pending-review
